// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication8.Data;

namespace WebApplication8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebApplication8.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("WebApplication8.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<byte[]>("AvatarImage");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Firstname");

                    b.Property<string>("FullName");

                    b.Property<int>("KitNumber");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<int>("MobilePhoneNumber");

                    b.Property<string>("Nickname");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Position");

                    b.Property<int?>("RelatedTeamteamId");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Surname");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("isRegistered");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RelatedTeamteamId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WebApplication8.Models.Comment", b =>
                {
                    b.Property<int>("commentid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RelatedMatchmatchid");

                    b.Property<string>("RelatedUserId");

                    b.Property<string>("commentUsername");

                    b.Property<string>("commentscontent")
                        .HasMaxLength(200);

                    b.HasKey("commentid");

                    b.HasIndex("RelatedMatchmatchid");

                    b.HasIndex("RelatedUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebApplication8.Models.Match", b =>
                {
                    b.Property<int>("matchid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RelatedTeam1teamId");

                    b.Property<int?>("RelatedTeam2teamId");

                    b.Property<DateTime>("dateTime");

                    b.Property<string>("location")
                        .IsRequired();

                    b.Property<string>("overtime")
                        .IsRequired();

                    b.Property<string>("penalty")
                        .IsRequired();

                    b.Property<string>("team1Name")
                        .IsRequired();

                    b.Property<int>("team1PenaltyScore");

                    b.Property<int>("team1Score");

                    b.Property<string>("team2Name")
                        .IsRequired();

                    b.Property<int>("team2PenaltyScore");

                    b.Property<int>("team2Score");

                    b.HasKey("matchid");

                    b.HasIndex("RelatedTeam1teamId");

                    b.HasIndex("RelatedTeam2teamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WebApplication8.Models.NewMatch", b =>
                {
                    b.Property<int>("newMatchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Overtime")
                        .IsRequired();

                    b.Property<string>("Penalty")
                        .IsRequired();

                    b.Property<DateTime>("dateTime");

                    b.Property<string>("location")
                        .IsRequired();

                    b.Property<string>("matchDescription")
                        .IsRequired();

                    b.Property<string>("matchType")
                        .IsRequired();

                    b.HasKey("newMatchId");

                    b.ToTable("NewMatches");
                });

            modelBuilder.Entity("WebApplication8.Models.PlayerPerformance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RelatedMatchmatchid");

                    b.Property<string>("RelatedUserId");

                    b.Property<int>("assists");

                    b.Property<int>("clearances");

                    b.Property<int>("goals");

                    b.Property<int>("keydribbles");

                    b.Property<int>("keypasses");

                    b.Property<string>("linkedTeamname")
                        .IsRequired();

                    b.Property<string>("linkedplayername")
                        .IsRequired();

                    b.Property<int>("redcard");

                    b.Property<int>("saves");

                    b.Property<string>("startup")
                        .IsRequired();

                    b.Property<string>("substitute")
                        .IsRequired();

                    b.Property<int>("yellowcard");

                    b.HasKey("id");

                    b.HasIndex("RelatedMatchmatchid");

                    b.HasIndex("RelatedUserId");

                    b.ToTable("PlayerPerformance");
                });

            modelBuilder.Entity("WebApplication8.Models.RegisteredUser", b =>
                {
                    b.Property<int>("RegisteredUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("AvatarImage");

                    b.Property<string>("Firstname");

                    b.Property<string>("FullName");

                    b.Property<int>("KitNumber");

                    b.Property<int>("MobilePhoneNumber");

                    b.Property<string>("Nickname");

                    b.Property<string>("Position");

                    b.Property<string>("RelatedTeamName");

                    b.Property<int?>("RelatedTeamteamId");

                    b.Property<string>("RelatedUserId");

                    b.Property<string>("Surname");

                    b.Property<string>("isRegistered");

                    b.HasKey("RegisteredUserId");

                    b.HasIndex("RelatedTeamteamId");

                    b.HasIndex("RelatedUserId");

                    b.ToTable("TeamRegisteredUsers");
                });

            modelBuilder.Entity("WebApplication8.Models.Team", b =>
                {
                    b.Property<int>("teamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("teamName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("teamId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("WebApplication8.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApplication8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApplication8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("WebApplication8.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApplication8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication8.Models.ApplicationUser", b =>
                {
                    b.HasOne("WebApplication8.Models.Team", "RelatedTeam")
                        .WithMany()
                        .HasForeignKey("RelatedTeamteamId");
                });

            modelBuilder.Entity("WebApplication8.Models.Comment", b =>
                {
                    b.HasOne("WebApplication8.Models.Match", "RelatedMatch")
                        .WithMany()
                        .HasForeignKey("RelatedMatchmatchid");

                    b.HasOne("WebApplication8.Models.ApplicationUser", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId");
                });

            modelBuilder.Entity("WebApplication8.Models.Match", b =>
                {
                    b.HasOne("WebApplication8.Models.Team", "RelatedTeam1")
                        .WithMany()
                        .HasForeignKey("RelatedTeam1teamId");

                    b.HasOne("WebApplication8.Models.Team", "RelatedTeam2")
                        .WithMany()
                        .HasForeignKey("RelatedTeam2teamId");
                });

            modelBuilder.Entity("WebApplication8.Models.PlayerPerformance", b =>
                {
                    b.HasOne("WebApplication8.Models.Match", "RelatedMatch")
                        .WithMany()
                        .HasForeignKey("RelatedMatchmatchid");

                    b.HasOne("WebApplication8.Models.ApplicationUser", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId");
                });

            modelBuilder.Entity("WebApplication8.Models.RegisteredUser", b =>
                {
                    b.HasOne("WebApplication8.Models.Team", "RelatedTeam")
                        .WithMany()
                        .HasForeignKey("RelatedTeamteamId");

                    b.HasOne("WebApplication8.Models.ApplicationUser", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
